.TH "BRIGHTNESSCTL" "1" "2024-11-18" "brightnessctl" "brightnessctl"

.SH "NAME"
brightnessctl \- read and control device brightness


.SH "SYNOPSIS"

.sp
\fIbrightnessctl\fR [options] \fI[operation]\fR [value...]


.SH "OPTIONS"

.sp
\fB\-h, \-\-help\fP
.RS 4
Print this help.
.RE

.sp
\fB\-l, \-\-list\fP
.RS 4
List devices with available brightness controls.
.RE

.sp
\fB\-q, \-\-quiet\fP
.RS 4
Suppress output.
.RE

.sp
\fB\-p, \-\-pretend\fP
.RS 4
Do not perform write operations.
.RE

.sp
\fB\-m, \-\-machine\-readable\fP
.RS 4
Produce machine\-readable output.
.RE

.sp
\fB\-P, \-\-percentage\fP
.RS 4
Display value as a percentage in get.
.RE

.sp
\fB\-n, \-\-min\-value\fP=\fI[VALUE]\fP
.RS 4
Set minimum brightness when using delta values. VALUE is set to 1 when not provided.
.RE

.sp
\fB\-e, \-\-exponent\fP=\fIK\fP
.RS 4
Changes percentage scaling curve to exponential (linear by default). Default exponent is 4.

Percentage equation: % = \fI[VALUE]\fR^\fI[K]\fR * \fI[MAX]\fR * 100^-\fI[K]\fR.

The exponential curve may make the adjustments perceptually equal.
.RE

.sp
\fB\-s, \-\-save\fP
.RS 4
Save state in a temporary file.
.RE

.sp
\fB\-r, \-\-restore\fP
.RS 4
Restore previously\-saved state.
.RE

.sp
\fB\-d, \-\-device\fP=\fIDEVICE\fP
.RS 4
Specify device name (can be a wildcard).

If device is specified as \fB'*'\fP, only \fBbrightness\fP class devices are selected.
.RE

.sp
\fB\-c, \-\-class\fP=\fICLASS\fP
.RS 4
Specify device class.
.RE

.sp
\fB\-V, \-\-version\fP
.RS 4
Print version and exit.
.RE

.sp
\fB\\-\-frac\fP
.RS 4
Output percentages as fractional values.
.RE


.SH "OPERATIONS"

.sp
\fBi, info\fP
.RS 4
Get device info.
.RE

.sp
\fBg, get\fP
.RS 4
Get the current brightness of the device.
.RE

.sp
\fBm, max\fP
.RS 4
Get the maximum brightness of the device.
.RE

.sp
\fBs, set\fP \fIVALUE\fP
.RS 4
Set the brightness of the device.

.SS VALUES
.P
You may specify \fIVALUE\fR for the \fBset\fR command in absolute or relative form, and
as a value or a delta from the current value. For example:
.P
\fBbrightnessctl set 500\fR
.RS "4"
Sets brightness to 500.
.P
.RE
\fBbrightnessctl set 50%\fR
.RS "4"
Sets brightness to 50% of the maximum.
.P
.RE
\fBbrightnessctl set 50-\fR
.RS "4"
Subtracts 50 from the current brightness.
.P
.RE
\fBbrightnessctl set +10\fR
.RS "4"
Adds 10 to the current brightness.
.P
.RE
\fBbrightnessctl set 50%-\fR
.RS "4"
Subtracts 50% of the maximum from the current brightness.
.P
.RE
\fBbrightnessctl set +10%\fR
.RS "4"
Adds 10% of the maximum to the current brightness.
.P
.RE
.SH AUTHORS
.P
Maintained by Mykyta Holubakha, who is assisted by other open source
contributors. For more information about brightnessctl development, visit:
.P
https://github.com/Hummer12007/brightnessctl
